### ISSUE TITLE
Battery Levels Discussion

### ISSUE THREAD

**Issue by jchasey** [custom-components/sensor.owlintuition#1]
Having just had a room thermostat go down due to low battery level, some thoughts on the best approach.
Room thermostat lost connection at 76% (2.76mV)
Tank thermostat still running fine at 66% (2.66mV)
Realised that the % used in these cases are just a direct translation of the mV level over 2v.
The Room thermostat however is a lot further away than the tank thermostat from the network Owl, so not entirely surprised that is the case.
The conclusion however is that rather than translating to low/medium/high values a % should be used to be both consistent and across devices and let the user create their own alerts etc, as the level this should be at will be dependent on their specific setup.

**Comment by glpatcern** [comment]
I see the point that a low/medium/high figure is too coarse-grained to be useful when different sensors drop off at different levels. And actually, we could even consider that a direct (linear) mV -> % conversion is inaccurate as most batteries drop their voltage more significantly towards their end-of-life.

As a matter of fact, I went for that coarse-grained approach following NetAtmo (which I use as well). But they do offer both a `battery` and a `battery-lvl` sensors. So why not implement the same? About doing some non-linear mV -> % conversion I'm less convinced though. What do you think?

**Comment by jchasey** [comment]
Agree a battery and battery-lvl makes sense and the user can then use the sensor most appropriate to them. 
I did some quick research on 'real' % and it varies too much across different battery makes to be anything accurate.
Therefore preference would be to keep as close to what OWL report, so ideally staying in mV for the heating and water sensors. The user can then use that or the coarse-grain if they want a consistent value?

**Comment by glpatcern** [comment]
Yeah, sounds like a good plan. Let's report data as we get it, and then users can do anything they like. Patch coming soon...
