### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rhyswillis1984** [custom-components/sensor.owlintuition#12]
I have added HACS to my HA and download Owl Intuition restarted the HA and left load but it is not showing in HA Integrations. I have checked the location and all looks good but is the folder inside custom_components mend to be sensor.owllintuition?

**Comment by glpatcern** [comment]
This integration is not meant to "automagically" show up in HA Integrations as it was written way earlier than that mechanism was put in place. Simply follow the instructions in `README.md` and edit your `configuration.yaml` following the doc to have the sensors appear in HA.

To be noted that you need to ensure the HA server is be able to listen for UDP traffic from OWL, so any firewall or NAT layer you may have needs to be configured accordingly. If the sensors never show any value and the HA logs include timeouts, [this thread](https://community.home-assistant.io/t/owl-intuition-pv-home-assistant/18157) is a good place to look for solutions and discuss.

**Comment by rhyswillis1984** [comment]
i have followed the the readme file and nothing is coming into the list to show on HA.

I have also add to configuration file.

Am i missing something?

**Comment by glpatcern** [comment]
> i have followed the the readme file and nothing is coming into the list to show on HA.

As said, nothing appears in the integrations list, but if the configuration is correct, new sensors are available (and would popup on an automatically-managed dashboard).

> Am i missing something?

What does the log file report, concerning this integration?

**Comment by rhyswillis1984** [comment]
Sorry i didn't mean the integrations.

When i go to overview and add card there is no sensor there or this.

There is nothing showing in the report file.  With the port is it the port the ha is on?

Sorry im new to all this and still learning

**Comment by glpatcern** [comment]
OK, if no sensor is appearing somehow the integration did not load - the log file `home-assistant.log` should report some error.

The port is the one you choose and set in the OWL portal (see README), not the HA port (so not the usual `8123`).

**Comment by rhyswillis1984** [comment]
I am sorry i found a fault with the code as i'm new to this.  I have just been playing around and have got it sorted.  Really sorry and than you for all your replys and help

**Comment by glpatcern** [comment]
No problem, good that you found the issue yourself with your configuration!
