### ISSUE TITLE
Solar Values

### ISSUE THREAD

**Issue by sjukes69** [custom-components/sensor.owlintuition#14]
Hi

I have the below code in my yaml config file which match the values I have entered in my owl dashboard

sensor:
  - platform: owlintuition
    port: 3200
    host: 192.168.0.71
    monitored_conditions:
      - solar
      - electricity
     
The reading for the total electricty used for the day shows correctly matching the owl app, however, all the sensors for solar are coming in as "Unknown" as per screen shot uploaded

Have missed a config step somewhere?

![owl](https://user-images.githubusercontent.com/80791996/116578444-532a1a00-a909-11eb-864a-478ccd69d1a6.jpg)

Thanks

Simon

**Comment by smondejar** [comment]
Hi, I had the same problem so I headed to the logs, It seems a version is not declared on the component's manifest.json file.
I just added the string with "1" as value and voila, all working again.
This is my manifest file:

`{
        "domain": "owlintuition",
        "name": "OWL Intuition",
        "version": "1",
        "documentation": "https://github.com/custom-components/sensor.owlintuition",
        "requirements": [],
        "dependencies": [],
        "codeowners": ["@glpatcern"]
}
`
Hope this helps, cheers.

**Comment by sjukes69** [comment]
> Hi, I had the same problem so I headed to the logs, It seems a version is not declared on the component's manifest.json file and HA wasn't loading the component because of it.
> 
> I just added the string using"1" as value and voila, all working again.
> This is my manifest file:
> 
> > {
> > "domain": "owlintuition",
> > "name": "OWL Intuition",
> > **"version": "1",**
> > "documentation": "https://github.com/custom-components/sensor.owlintuition",
> > "requirements": [],
> > "dependencies": [],
> > "codeowners": ["@glpatcern"]
> > }
> 
> Hope this helps, cheers.

Hi

Thanks for your reply

Unfortunatly, adding version to the yaml file made no difference, still no solar values

Thanks anyway

Simon

**Comment by smondejar** [comment]
> > Hi, I had the same problem so I headed to the logs, It seems a version is not declared on the component's manifest.json file and HA wasn't loading the component because of it.
> > I just added the string using"1" as value and voila, all working again.
> > This is my manifest file:
> > > {
> > > "domain": "owlintuition",
> > > "name": "OWL Intuition",
> > > **"version": "1",**
> > > "documentation": "https://github.com/custom-components/sensor.owlintuition",
> > > "requirements": [],
> > > "dependencies": [],
> > > "codeowners": ["@glpatcern"]
> > > }
> > 
> > 
> > Hope this helps, cheers.
> 
> Hi
> 
> Thanks for your reply
> 
> Unfortunatly, adding version to the yaml file made no difference, still no solar values
> 
> Thanks anyway
> 
> Simon

Are you adding it to the manifest.json file?

Path for this file is as in [this screenshot ](https://imgur.com/a/cSjFrhv).

**Comment by sjukes69** [comment]
Hi, after starting over and re-installing the integration, everything is working now
Thanks

**Comment by glpatcern** [comment]
Great to hear you sorted it out (and apologies for not replying earlier, I somehow missed the first notification).

Meanwhile I also updated the manifest to include the version as required by HA now.
