### ISSUE TITLE
Unable to use for Home Assistant Energy feature

### ISSUE THREAD

**Issue by psl3** [custom-components/sensor.owlintuition#17]
Have this add on generally working but I cannot use it with the Energy feature in latest builds - when selecting Electricity use or solar generated -- the Energy feature only lists the Elec or solar TODAY not the actual at the time which is needed.

There is some info on needing to add some attributes to the owl code but I do not understand -- just great to use these components that this incredibly talented people can create. Here is the page it suggests needs to be looked at 
https://www.home-assistant.io/more-info/statistics/

I'm using Solar generated, Solar exported and total electricity used from the owl system.   
Thanks very much if this could be looked at!

**Comment by shortbloke** [comment]
@psl3 If you look at #16 you should see this is working (well for me anyway), with the latest Owl Intuition component version, and the latest HA. Have you updated to the latest version?

**Comment by psl3** [comment]
Thanks shortbloke. I was expecting to use the instantaneous values rather than the cumulative entities (e.g. Today) but see it is the 3 x xxxTODAY entities that are expected to work. I still have issues but will add to #16
