### ISSUE TITLE
2nd Hot Water Sensor - how to get the data?

### ISSUE THREAD

**Issue by LankyGamer83** [custom-components/sensor.owlintuition#23]
Hi all,
Since I got my Dad into the World of HA and seeing OWL data via this component - he's bought a 2nd hot water sensor - which he can see in the Owl App - but its not appearing in HA.
Looking at the code (I never did get on with python....) - i'm guessing its missing the filters to grab the 2nd sensor? Anyone know what to change to make HA see it?
EDIT: I am going try and go round there and re-direct the XML to his PC to see what it looks like - if that would help.
Thanks

**Comment by HBuk** [comment]
Hot Water element of XML attached:
<hot_water ver='2' id='443719005B87'>
		<timestamp>1655024306</timestamp>
		<zones>
			<zone id='20029D2' last='42'>
				<signal rssi='-26' lqi='48'/>
				<battery level='2970'/>
				<conf flags='0'/>
				<temperature state='0' flags='0' until='0'>
					<current>61.50</current>
					<required>42.00</required>
					<ambient>34.11</ambient>
				</temperature>
			</zone>
			<zone id='2002A20' last='1'>
				<signal rssi='-27' lqi='47'/>
				<battery level='2990'/>
				<conf flags='0'/>
				<temperature state='0' flags='0' until='0'>
					<current>73.00</current>
					<required>42.00</required>
					<ambient>33.68</ambient>
				</temperature>
			</zone>
		</zones>
	</hot_water>

**Comment by glpatcern** [comment]
Sorry for the extremely late reply, I'll review the GitHub notifications on this project. Thanks for the XML, it's going to be super useful to implement the necessary parsing, that seems quite straightforward.

**Comment by glpatcern** [comment]
For convenience:

```
<hot_water ver='2' id='443719005B87'>
	<timestamp>1655024306</timestamp>
	<zones>
		<zone id='20029D2' last='42'>
			<signal rssi='-26' lqi='48'/>
			<battery level='2970'/>
			<conf flags='0'/>
			<temperature state='0' flags='0' until='0'>
				<current>61.50</current>
				<required>42.00</required>
				<ambient>34.11</ambient>
			</temperature>
		</zone>
		<zone id='2002A20' last='1'>
			<signal rssi='-27' lqi='47'/>
			<battery level='2990'/>
			<conf flags='0'/>
			<temperature state='0' flags='0' until='0'>
				<current>73.00</current>
				<required>42.00</required>
				<ambient>33.68</ambient>
			</temperature>
		</zone>
	</zones>
</hot_water>
```
