### ISSUE TITLE
Getting an error in HA since doing the 2023.6.0 update

### ISSUE THREAD

**Issue by BertrumUK** [custom-components/sensor.owlintuition#30]
![image](https://github.com/custom-components/sensor.owlintuition/assets/22644029/d23b5f3e-5093-4347-8fd4-2d40f58db38b)

Disabling the sensor config clears the error -

#- platform: owlintuition
  #host: 192.168.1.154
  #port: 4321
  #mode: monophase
  #monitored_conditions:
    #- electricity
    #- solar

**Comment by BertrumUK** [comment]
[Look here](https://docs.python.org/3.8/library/asyncio-task.html#asyncio.coroutine)

**Comment by wcavanagh** [comment]
Seeing the same here

**Comment by orandaadnaro** [comment]
Hi I keep dipping in and out of here and I'm not too sure if I understand what is going on here:

By commenting out in configuration.yaml does the owl stuff work or does it simply stop HA from crashing on a reboot when using the 2023.6.0 update.

Ive reverted to 2023.4.6 as suggested earlier, and this works for me.

**Comment by BertrumUK** [comment]
The Owl sensor does not work with 2023.6.0. I was just stating that I get no other HA errors when I disable the Owl sensor.

**Comment by orandaadnaro** [comment]
Any news about when Owl will catch up with these newer updates?

**Comment by BertrumUK** [comment]
> Any news about when Owl will catch up with these newer updates?

This is nothing to do with Owl. The Code owner or someone who knows more about Python will right the fix shortly I am guessing.

**Comment by shortbloke** [comment]
Python 3.11 introduced in HA 2023.6.0 is likely to break a number of components. I looked at the release notes and decided to wait until I could build a second HA instance, rather than risk breaking stuff. 

If @glpatcern doesn't get a chance, I may have time tomorrow to fix this up and submit a PR.

**Comment by glpatcern** [comment]
This definitely is a significant breaking change. Will see what I or @shortbloke can do, but until then I rather suggest to revert to the latest-1 release. I have myself another custom component and it will likely break as well with Python 3.11.

BTW I'm seriously thinking that we could contribute this integration to HA core. It would require some work to ease the config, but it will be supported by the community.

**Comment by BertrumUK** [comment]
I can confirm that removing line 167 "@asyncio.coroutine" fixes this issue (for now) 👍

**Comment by wcavanagh** [comment]
Where do we remove a line to get round this for now please?

**Comment by BertrumUK** [comment]
> Where do we remove a line to get round this for now please?

As per my last update, remove line 167 in sensor,py and restart HA.
