### ISSUE TITLE
"OWL Intuition Electricity Today" and "OWL Intuition Electricity Today P1" show same value

### ISSUE THREAD

**Issue by thotha** [custom-components/sensor.owlintuition#35]
HA Core 2023.12.3
HA Supervisor 2023.11.6
HA Operating System 11.2
HA Frontend 20231208.2
OWL Intuition Component 1.6.0
Save Energy Limited OWL Intuition Device Version 1.5
Save Energy Limited System Type: Intuition-e
Save Energy Limited Network OWL: v4.3 build 630

Hello Giuseppe

I have the problem, that the value "OWL Intuition Electricity Today" does show the same as "OWL Intuition Electricity Today P1". Based on the name I would expect that "OWL Intuition Electricity Today" does show the sum of "OWL Intuition Electricity Today P1" to "OWL Intuition Electricity Today P3". Also as you can see in the screenshot, the "Grid total" does show the sum of "OWL Intuition Electricity Today" to "OWL Intuition Electricity Today P3" which is also wrong.
![Ohne Titel](https://github.com/custom-components/sensor.owlintuition/assets/17160749/1ad4087e-d243-4843-a25b-0566d94d958a)

sensor:
  - platform: owlintuition
    port: 61092
    host: 192.168.105.1
    mode: triphase
    cost_icon: 'mdi:currency-eur'
    cost_unit_of_measurement: CHF
    monitored_conditions:
      - electricity
 
Then I have a question about cost calculations.
Does your component take that cost calculations from the OWL Intuition Device calcualtion entries or is there an other way to define the cost per day and time range?

Kind regards
Thomas

**Comment by shortbloke** [comment]
@thotha the values come from the data sent by the owl intuition device they aren't calculated by this component.

I recall when setting up the owl intuition device on https://www.owlintuition.com/ I had to specify how the system was configured,  does the official web site show the expected values and is it configured for your 3 phase setup?

**Comment by glpatcern** [comment]
Closing as there was no follow up question after the provided answer.
