### ISSUE TITLE
Sensors not updating

### ISSUE THREAD

**Issue by smondejar** [custom-components/sensor.owlintuition#36]
Hi, I updated my HAOS hardware to a Rpi5 and everything works perfectly using the latest release but I have found that the owlintuition sensors are showing initial data but not updating.
If I reload the integration or the system, the integration picks the values up but it will not update values anymore.

Has anyone experienced a similar behaviour or is there a known reason why this could be happening?

TIA

HAOS Core: 2024.1.1, Rpi5 - Latest sensor.owlintuition integration release.

**Comment by richardmaidment** [comment]
I updated HA to 2024.1 last week from 2023.12.4 and observed the same thing.  Initially the values load but don't subsequently update.  I rolled back as I have some automations that boost the hot water when there's a call for heat and this issue resulted in a cold bath for my wife!

I'm expectng that there's something in HA 2024.1 that's causing this as I expect you took the latest version when building your new RP?

I'm not sure how to troubleshoot this?

**Comment by smondejar** [comment]
Hey @richardmaidment, thank you for your reply

> I'm expectng that there's something in HA 2024.1 that's causing this as I expect you took the latest version when building your new RP?

I got the latest version indeed, the Rpi5 required it hardware wise and I have to say it is fantastic, blazing fast.
Unfortunately I am not code-savvy so I can only post the owlintuition related logs, which are basically a constant flow of:

`2024-01-07 18:50:16.570 WARNING (MainThread) [homeassistant.components.sensor] Updating owlintuition sensor took longer than the scheduled update interval 0:00:30
2024-01-07 18:50:21.539 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.owl_intuition_solar_exported_today is taking over 10 seconds`

Multicast flow from the OWL is fine, I tested with some monitoring programs, all of them are getting the data.

As a workaround, I will probably re-install in my old Rpi4, so I can get the integration working and embed the power dashboard into the new installation.

**Comment by richardmaidment** [comment]
It does sound like teh same issue.

You should be able to put a different version on your Pi by laucing a SSH session and using the following command

ha core update --version 2023.12.4

This is how I got back to working, I prefer this to restoring a from a backup.

**Comment by maknij** [comment]
I'm also seeing the same behaviour since upgrading to 2024.1

**Comment by smondejar** [comment]
As a workaround, I have installed version 2023.11 in a Pi Zero I had lying around and used HACS remote_homeassistant integration to pull the entities data from 2024.1.1 (Rpi5). 

[https://github.com/custom-components/remote_homeassistant](url)

It works fine and the entity names, once owlintuition has been uninstalled from the main instance, are the same so everything just came to life.

I'll keep this setup for now until a more clever being finds a permanent fix.

**Comment by shortbloke** [comment]
I've started looking into this issue. The custom component is correctly receiving the datagrams from the intuition owl. I've tried fixing up the code to remove some deprecation warnings, but whilst that's addressed the warnings, the sensor still only get updated once. More investigation is required.

**Comment by shortbloke** [comment]
I've opened a ticket against homeassistant.core: https://github.com/home-assistant/core/issues/107608

**Comment by shortbloke** [comment]
I've created a PR, but only had time to do limited testing. Need the sun to shine to get some Solar data ;-) 

I'd welcome some more beta testers for this change, grabbing the sensor.py from the [PR branch](https://github.com/custom-components/sensor.owlintuition/pull/37), add replacing the version in your `custom_components\owlintuition` folder and restarting HomeAssistant should do the trick.

**Comment by shortbloke** [comment]
@orandaadnaro 
Download the file from the PR [sensor.py](https://raw.githubusercontent.com/custom-components/sensor.owlintuition/40b461130c8b91176978be4de68682b754bd6509/custom_components/owlintuition/sensor.py)

Then replace the sensor.py in the `custom_components\owlintuition` folder. Depending on what you have setup you could replace this file using SSH, Samba or even copy and paste to write out the new file. 
Then restart HomeAssistant and/or upgrade to the latest HA release if you're not already on it.

**Comment by orandaadnaro** [comment]
No probs - Ill give it a go - report back when Ive had a few hours of sunshine

**Comment by smondejar** [comment]
Hey @shortbloke, thanks for your help, it seems to be working fine, is updating values every minute or so, at least the power/energy readings.
I'll leave it running and report if anything.

**Comment by tluethi71** [comment]
I will try tomorrow morning as well. Question: has the loooong waiting time to have the sensor.owlintuition loaded to do with this issue? since I have deleted owlintuition yesterday due to the issue HA OS is restarting less than 1 Minute. With owlintuition the restart takes around 5 minutes..

**Comment by richardmaidment** [comment]
Looking good here too.  I use heating and hot water.

I initially tried with HA 2023.12.4 and it didn't seem to work so bumped up to 2024.1.2 and all seemed good.

Thanks for fixing this.  I keep feeling my Owl Intuition heating controls are on borrowed time as Owl haven't made any changes to the app for years.  I like how it works though, especially the hot water with scheduled time periods at different temperatures and with this integration I can extend the functionality further with automations.

**Comment by smondejar** [comment]
2024.1.2 has been working perfectly fine, updated to 2024.1.3 and it broke it again, rolled back to 2024.1.2.

**Comment by orandaadnaro** [comment]
I too had problems and removed and reinstalled the fill custom components/owl intuition folder from GitHub, and now when I check the configuration I get on check and restart in HA:

Configuration warnings
Platform error 'sensor' from integration 'owlintuition' - Exception importing custom_components.owlintuition.sensor

And no data coming through :-(

**Comment by coleburg** [comment]
Hi, Ive copied over the file and its still erroring for me, im using 
Core
2024.1.3
Supervisor
2023.12.0
Operating System
11.4
Frontend
20240104.0

**Comment by shortbloke** [comment]
@coleburg @orandaadnaro @smondejar Can you try with the latest [sensor.py](https://raw.githubusercontent.com/custom-components/sensor.owlintuition/39ec31013bd0e602dafbeba57fdb071a1f15acbd/custom_components/owlintuition/sensor.py) from the pending Pull Request?

**Comment by coleburg** [comment]
> @coleburg @orandaadnaro @smondejar Can you try with the latest [sensor.py](https://raw.githubusercontent.com/custom-components/sensor.owlintuition/39ec31013bd0e602dafbeba57fdb071a1f15acbd/custom_components/owlintuition/sensor.py) from the pending Pull Request?

Works perfectly, thank you

**Comment by orandaadnaro** [comment]
> @coleburg @orandaadnaro @smondejar Can you try with the latest [sensor.py](https://raw.githubusercontent.com/custom-components/sensor.owlintuition/39ec31013bd0e602dafbeba57fdb071a1f15acbd/custom_components/owlintuition/sensor.py) from the pending Pull Request?

I couldn't cut and paste  the linked sensor.py into the HA file editor for some reason, but the Studio code server took the copy. I'm in the process of restarting my HA on my PI, , but as is sods law the sun has just gone down, here in the UK! So I'm not sure what to expect to see  on the HA Energy option?

On the  Overview option there is now a range of outputs - so presumably something is working - at least a lot more than I've had over the past few day!

I'll feedback more in the morning :-)

 ...

**Comment by smondejar** [comment]
Hey @shortbloke I can confirm latest [sensor.py](https://raw.githubusercontent.com/custom-components/sensor.owlintuition/39ec31013bd0e602dafbeba57fdb071a1f15acbd/custom_components/owlintuition/sensor.py) from PR works fine on 2024.1.3, all energy/power sensor working

**Comment by orandaadnaro** [comment]
All APPEARS TO BE WORKING WELL - THANKS

**Comment by orandaadnaro** [comment]
Core Update 2024.1.4 has turned up on my HA - Dare I update or should I wait?

**Comment by shortbloke** [comment]
@orandaadnaro I have updated to 2024.1.4 and the integration continues to work

**Comment by orandaadnaro** [comment]
Working here too - thx!
