### ISSUE TITLE
Stopped working after HA Update

### ISSUE THREAD

**Issue by wcavanagh** [custom-components/sensor.owlintuition#39]
I don’t seem to be getting any readings from my device since the last HA update.  Anyone else have an issue?

**Comment by shortbloke** [comment]
Still working for me: 
- Core: 2024.2.5
- Supervisor: 2024.02.1
- Operating System: 12.0
- Frontend: 20240207.1

With owl intuition component version: b479dc3

**Comment by wcavanagh** [comment]
Core
2024.2.5
Supervisor
2024.02.1
Operating System
12.0
Frontend
20240207.1

Owl version b479dc3

logs say

**Comment by shortbloke** [comment]
@wcavanagh You don't appear to have included the logs

**Comment by wcavanagh** [comment]
Oh sorry, the only thing in the error log after a fresh startup is .

2024-03-06 09:02:24.717 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration owlintuition which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

All the Owl sensors say Entity Not Available.    Owl is working as I can see in the app and website all online etc.

**Comment by wcavanagh** [comment]
Thank you i have added that, and still no errors seen in the log, but still not data in the sensors.  I cam going to reboot the owl next to see if that helps.

**Comment by shortbloke** [comment]
Do you still have a subscription to the Owl Intuition Website? If so is data appearing there?

**Comment by wcavanagh** [comment]
Yes, all live and active, and I see data there too.  I’ve checked IPs and they are fixed so no change, and port number is correct. Was working until the HA update.  Rebooting didn’t not help.

**Comment by shortbloke** [comment]
If you aren’t seeing any debug logs, it suggests the UDP packets aren’t being received. Any other network changes?

**Comment by wcavanagh** [comment]
Nothing at all, everything is the same on network level. Both the owl website and app are working. Not a single log in HA.  Not config changes other than the last update. Might try rolling back and see what happens.

**Comment by wcavanagh** [comment]
Will pop wireshark on and see if I can see any UDP packets at all.

**Comment by wcavanagh** [comment]
Well interesting, I can see USD only going to the internet and nothing on LAN.

![Screenshot 2024-03-07 124936](https://github.com/custom-components/sensor.owlintuition/assets/58342287/0efd17e1-44c3-4239-a556-9ccc80af6a41)

**Comment by orandaadnaro** [comment]
Core
2024.3.0
Supervisor
2024.02.1
Operating System
12.0
Frontend
20240306.0

Mine has stopped too :-(

**Comment by wcavanagh** [comment]
Oh interesting, I’ve contacted owl support to see if they changed anything.  Did yours stop after HA update?

**Comment by wcavanagh** [comment]
They say they have made no new changes to the Owl software.  So still somehow points to HA.  I am at a loss.

**Comment by wcavanagh** [comment]
So using the owls sniffer tool, I can see multicast data being sent out on the network from Owl, so the Owl is working
![Screenshot 2024-03-07 183617](https://github.com/custom-components/sensor.owlintuition/assets/58342287/9db60c7d-9b4d-4d3f-b7f6-8c41927fe7dc)
 well.

**Comment by wcavanagh** [comment]
Will lest the java UDP listener next, then if that works it HAS to be a HA issue

**Comment by shortbloke** [comment]
How do you have your Owl configured? Mine is configured to send packets to my HA instance (192.168.200.45)
![image](https://github.com/custom-components/sensor.owlintuition/assets/13274408/a1743327-cbf0-46f2-8d62-4dd0238d2a65)

```yaml
# Owl Energy Monitor
- platform: owlintuition
  host: 192.168.200.45
  port: 32000
  mode: triphase
  cost_icon: 'mdi:currency-gbp'
  cost_unit_of_measurement: GBP
  monitored_conditions:
    - electricity
    - solar
```

I know it can be used in a multicast mode too. I'm wondering if one mode has broken?

**Comment by wcavanagh** [comment]
I have mine like yours, IP and port, will have a look if i can change to multicast, as that is defiantly working according to my tests.

**Comment by wcavanagh** [comment]
Looks like I just take the port out to enable multicast, just rebooting HA now :)

**Comment by wcavanagh** [comment]
No joy still, yet i know for sure the multicast is being sent over the network, same switch PC, HA, and OWL

**Comment by orandaadnaro** [comment]
This may be coincidental, but I have lost connection to owl recently. On checking this evening  I discovered my subscription had lapsed. 

I've just now renewed my subscription, so it may be interesting to see if I get any data appearing on my energy page.

You may want to check if you have an active subscription?

**Comment by wcavanagh** [comment]
Interesting, I have double checked and mine is still active

Subscription Expiry | 25/02/2025

**Comment by shortbloke** [comment]
Have you tried to power cycle the owl receiver? 
Also long shot but if you're using something like pfsense for your router, then maybe worth rebooting it too. 
I don't suppose the owl and HA are on different subnets/vlans?

**Comment by orandaadnaro** [comment]
I’ll try in the morning. Its dark now and I doubt if I’ll see anything appear on the energy page.

**Comment by wcavanagh** [comment]
All on the same VLAN, yes power cycled the OWL, router would not cause an issue as it in internal LAN-LAN 

All very weird. Its like HA just don see the multicast message.

**Comment by orandaadnaro** [comment]
Last night I resubscribds to Owl and restarted my owl unit and this morning all appears well - energy data being plotted on the graph.

Why should HA be dependeant on an active owl subscription. Where does it get it data from?

**Comment by shortbloke** [comment]
@orandaadnaro I had the same issue more than once. I believe the owl stops emitting UDP packets when the subscription has expired. I'm not sure if this only applies to the directed UDP packets, vs a UDP multicast (which I think was the default config). Each time it's happened, I've been busy and just paid the sub and moved on.

**Comment by wcavanagh** [comment]
No joy here still.

**Comment by wcavanagh** [comment]
So I changed the Owl to send the Push UDP to my PC also on the same network as HA, and run the Java program, I can see it pushing both UDP and Multicast, so for sure OWL is working correctly, just HA don't seem to see the data.  Pulling my hair out now.
![Screenshot 2024-03-09 200930](https://github.com/custom-components/sensor.owlintuition/assets/58342287/e4117fab-0a49-486f-8370-988582163aa5)

**Comment by wcavanagh** [comment]
Just to add further tests, a quick node red setup receives the data into HA
![Screenshot 2024-03-10 202344](https://github.com/custom-components/sensor.owlintuition/assets/58342287/4b1aeb0e-c3e2-4a75-9ef7-cf25d41e9d9e)

**Comment by orandaadnaro** [comment]
I’d be interested in seeing the raw code for your node red solution. It appears to be very compact. Any chance of t
You dropping it here?

**Comment by wcavanagh** [comment]
Sure no problem, I have now configured it complete without the need for the plugin :)

**Comment by wcavanagh** [comment]
Hi, 
I dont think its cool to share here in the Git of a integration, as what I created doesn't need the integration anymore.  Maybe I can sent private ? somehow

**Comment by glpatcern** [comment]
Hi @wcavanagh, reviewing this old issue I think it would be good to share more details as a separate discussion: could you please post your solution in #42 ?
Otherwise, I'm closing this as I understand this integration works even with the latest HA updates (see e.g. PR merged today).
