### ISSUE TITLE
Support for 3-Phase Power

### ISSUE THREAD

**Issue by BenWoodford** [custom-components/sensor.owlintuition#9]
It would be great to get an option to use the 3-channel mode for those of us with the 3-phase Owl meter. Instead of using the `electricity.property.current.watts` you use channels 0, 1 and 2 of the `electricity.channels.chan` XML data.

**Comment by glpatcern** [comment]
Hi,
Actually this is already provided by the sensor, you just need to use the `triphase` mode. See https://github.com/custom-components/sensor.owlintuition/blob/master/sensor.owlintuition.markdown for details.

**Comment by BenWoodford** [comment]
Ah! Sorry, missed that when I was browsing.

**Comment by glpatcern** [comment]
No problem!
